[package]
name = "hedgehog-splitmix-wasm"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
description = "WebAssembly bindings for SplitMix64 PRNG"
repository = "https://github.com/justanotherdot/typescript-hedgehog"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]

[profile.release]
# Optimize for size and performance
opt-level = 3
lto = true